name: Run unit tests

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set [ENVIRONMENT] variables
      run: |
        echo "Running unit tests..."

    - name: Build
      run: cargo build --verbose
      working-directory: ./

    - name: Run tests
      run: cargo test --verbose
      working-directory: ./
